### ISSUE TITLE
Updating from 2.3.X to 3.0.X breaks

### ISSUE THREAD

**Issue by SElab2019** [eclipse-ee4j/jaxrs-api#822] opened 2019-12-19 15:54 UTC
When I try to upgrade byte-buddy from 1.5.7 to the version after 1.6.3. The following code breaks.
```
    private Optional<CtMethod> getAnnotatedMethod(CtMethod method) {
        if (method.hasAnnotation(GET.class) || method.hasAnnotation(POST.class) ||
                method.hasAnnotation(PUT.class) || method.hasAnnotation(DELETE.class) ||
                method.hasAnnotation(HttpMethod.class)) {
            return Optional.of(method);
        }
        final CtClass declaringClass = method.getDeclaringClass();
        try {
            for (CtClass classInterface : declaringClass.getInterfaces()) {
               if (classInterface.hasAnnotation(Path.class)) {
                    return Optional.of(classInterface.getDeclaredMethod(method.getName(), method.getParameterTypes()));
               }
            }
        } catch (NotFoundException e) {

        }

        return Optional.empty();
    }
```

The code should pass, but it throws an error:
```
error: reference to NotFoundException is ambiguous
[ERROR] both class javax.ws.rs.NotFoundException in javax.ws.rs and class javassist.NotFoundException in javassist match
```

**Comment by mkarg** [comment] 2019-12-19 16:27
This does not seem to be caused by JAX-RS itself. Do you have a proof that this is really related to *our* sphere of control?

**Comment by spericas** [comment] 2019-12-20 14:52
This is clearly not JAX-RS related, please close.

**Comment by mkarg** [comment] 2019-12-20 15:00
Closing as requested by @spericas.

**Closed by mkarg** 2019-12-20 15:00 UTC
