### ISSUE TITLE
Missing license and notice files in api jars

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jaxrs-api#712] opened 2018-12-10 14:08 UTC
from https://www.eclipse.org/projects/handbook/#legaldoc-distribution

> The distribution form of software artifacts (often in a compiled form) generated from a project’s source code repositories must also include legal information.

**Comment by mkarg** [comment] 2018-12-11 06:40
Thanks for reporting this legal issue! I wonder why neither the EMO nor the PMC ever noticed that in the release review... ;-)

**Comment by mkarg** [comment] 2018-12-16 12:11
@jansupol Please check the staged 2.1.4: Can we close this issue?

**Comment by mkarg** [comment] 2018-12-29 13:08
@jansupol "ping" ;-)

**Comment by jansupol** [comment] 2019-01-04 19:03
Actually, I cannot see the legal docs in [2.1.4](https://oss.sonatype.org/content/groups/staging/jakarta/ws/rs/jakarta.ws.rs-api/2.1.4/jakarta.ws.rs-api-2.1.4.jar)

**Comment by mkarg** [comment] 2019-01-05 13:34
@jansupol You are right, these is missing. I will investigate at which point those got stripped from the JAR. Thanks for checking! :-)

**Comment by mkarg** [comment] 2019-01-07 06:44
Apparently `maven.multiModuleProjectDirectory` is not evaluated at runtime on the EF's Jenkins instance. This is weird, because the running Maven version is 3.5.4, and that property was introduced in 3.3 already. I will ask team Maven what could be the cause.

**Comment by jansupol** [comment] 2019-01-07 16:52
The property `maven.multiModuleProjectDirectory` points to the actual directory, not to the top most project directory. I assume the jenkins job is executed from `jaxrs-api/pom.xml` and hence the actual folder is different from the pom.xml folder. Hence, `maven.multiModuleProjectDirectory/..` does not point to the legal doc files folder. Either the release job or the maven pom needs to be changed

**Comment by mkarg** [comment] 2019-01-07 18:43
It seems the problem is different. I tried *locally on my laptop* by starting maven in the topmost folder, and provided `-f jaxrs-api/pom.xml`, and it worked like a charm, just like it would when starting directly in the "correct" folder and just giving no `-f` at all. That is just what the EF Jenkins does, too.

But while it correctly resolves `maven.multiModuleProjectDirectory` on my laptop, it does **not resolve at all** (i. e. not even *incorrectly resolve*) that parameter on the EF Jenkins:
```
[DEBUG] Added resource: /home/hudson/genie.jaxrs/.jenkins/jobs/mkarg-experimental-cleanbuild/workspace/jaxrs-api/${maven.multiModuleProjectDirectory}/..
```
As you can see, the EF Jenkins just copies the syntax *literally* instead of parsing it. On my latop it correctly writes the *resolved* path! So it seems the EF Jenkins is buggy. The strange thing is that the Maven version is the same as mine, also the version of the build helper plugin.

**Comment by chkal** [comment] 2019-01-08 05:04
Why do we use `${maven.multiModuleProjectDirectory}` even if this isn't a multi-module project? Is there any specific reason for that? I just created #720 to replace it with `${project.basedir}` which should definitely work even on Jenkins.

**Comment by jansupol** [comment] 2019-01-08 17:47
Right, no reason to point to `${maven.multiModuleProjectDirectory}` as JAX-RS project does not have modules

**Comment by mkarg** [comment] 2019-01-10 05:59
@jansupol Please check https://oss.sonatype.org/content/repositories/snapshots/jakarta/ws/rs/jakarta.ws.rs-api/2.1.5-SNAPSHOT/jakarta.ws.rs-api-2.1.5-20190110.054840-1.jar. LGTY?

**Comment by jansupol** [comment] 2019-01-15 13:19
Yes, it looks good. TCK passed.

**Comment by mkarg** [comment] 2019-01-19 19:08
Done with 2.1.5, closing.

**Closed by mkarg** 2019-01-19 19:08 UTC
Labels: bug, project
