### ISSUE TITLE
Malformed Request Body For Large Post Bodies

### ISSUE THREAD

**Issue by kira98k** [eclipse-ee4j/jaxrs-api#966] opened 2021-05-16 04:19 UTC
The below issue occurs in the latest version '3.0.2'. These are my dependencies : 
```gradle
dependencies {
    compile "org.glassfish.jersey.core:jersey-client:3.0.2"
    implementation 'org.glassfish.jersey.inject:jersey-hk2:3.0.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
}
```
When the below post request is executed the request body received at the server is malformed for any entity with length greater than or equal to 65840.
```java
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.Entity;
import jakarta.ws.rs.core.Response;

public class MyClass {
    public static void main(String[] args) {
        Client client = ClientBuilder.newClient();
//        int count = 65839; // Works
        int count = 65840; // Doesn't work
        String body = new String(new char[count]).replace("\0", "A");
        assert (body.length() == count);
        Response response = null;
        try {
            response = client.target("http://localhost:8888/")
                    .request()
                    .post(Entity.text(body));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
To reproduce the issue run a server, `nc -l 8888 > output.txt` and then run the java code.
The output looks like the following:
```http
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPOST / HTTP/1.1
Content-Type: text/plain
User-Agent: Jersey/3.0.2 (HttpUrlConnection 1.8.0_212)
Host: localhost:8888
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 65840

AAAAAAAAAAAAAAAAA... (Rest Of The Body)
```

While for any body with length less than 65840, the output looks like:
```http
POST / HTTP/1.1
Content-Type: text/plain
User-Agent: Jersey/3.0.2 (HttpUrlConnection 1.8.0_212)
Host: localhost:8888
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 65839

AAAAAAAAAAAAAAAAA... (Rest Of The Body)
```

**Comment by kira98k** [comment] 2021-05-16 04:21
I'm using the version "3.0.2"

**Comment by mkarg** [comment] 2021-05-16 07:35
Are you sure this is a generic JAX-RS problem? It more looks like a bug of your specific product. Have you tried to reproduce with a different product?

**Comment by kira98k** [comment] 2021-05-16 09:58
I tried it with RESTeasy Client which also has this issue and Apache CFX client which doesn't have this issue.
But both of these implement the Javax version of the JAX-RS API. Can you suggest any implementation of Jakarta where I can test this?

**Comment by kira98k** [comment] 2021-05-16 10:04
I also tested this in Jersey client version 2.x which uses Javax and its also an issue in that.

**Comment by kira98k** [comment] 2021-05-16 10:22
This is the response I got when I used the Apache CFX client. 
```http
POST / HTTP/1.1
Content-Type: text/plain
Accept: */*
User-Agent: Apache CXF 3.0.15
Cache-Control: no-cache
Pragma: no-cache
Host: localhost:8888
Connection: keep-alive
Transfer-Encoding: chunked

ff9
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA......
ff9
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA......
ff9
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA......
.
.
.
```

**Comment by spericas** [comment] 2021-05-17 14:50
@kira98k I see that you opened https://github.com/eclipse-ee4j/jersey/issues/4796 I will close this one as this is an implementation problem AFAICT.

**Closed by spericas** 2021-05-17 14:50 UTC
