### ISSUE TITLE
Problem with maven central

### ISSUE THREAD

**Issue by titusthefox04** [eclipse-ee4j/jaxrs-api#627] opened 2018-05-08 17:07 UTC
String  ${packaging.type} not resolved create problem in maven central and in sbt project.
 
<img width="235" alt="jax-ws-problem2" src="https://user-images.githubusercontent.com/22959765/39771538-d8038772-52f2-11e8-873c-f556a7dae746.png">

<img width="181" alt="jax-ws-problem" src="https://user-images.githubusercontent.com/22959765/39771537-d7e650a8-52f2-11e8-8891-d31e96076f6b.png">

**Comment by chkal** [comment] 2018-05-09 04:40
This is a duplicate of #572 and #571.

I think this is actually a sbt bug. Maven (and Gradle?) can handle this dynamic packaging type correctly.

**Comment by mkarg** [comment] 2018-05-11 15:57
@spericas Do you know why we don't simply use `<packaging>jar</packaging>` instead?

**Comment by chkal** [comment] 2018-05-11 16:17
AFAIK there is a special Java 9 profile which uses a different packaging type.

See: https://github.com/eclipse-ee4j/jaxrs-api/blob/d2cadd2a5b22b4c7922a3f1d7c5e00506fccdd75/jaxrs-api/pom.xml#L144-L152

**Comment by mkarg** [comment] 2018-05-11 16:50
Looks like this was done solely to make the OSGi packager (bnd) work as it is so outdated that it cannot handle JDK 9. I don't like that solution. OSGi is not part of neither Jakarta EE nor JAX-RS. I'd rather kick OSGi out right now. But what do others think?

**Comment by chkal** [comment] 2018-05-13 07:59
> Looks like this was done solely to make the OSGi packager (bnd) work as it is so outdated that it cannot handle JDK 9.

Yeah, looks like this was the reason for introducing the dynamic packing type.

> I don't like that solution. OSGi is not part of neither Jakarta EE nor JAX-RS. I'd rather kick OSGi out right now. But what do others think?

AFAIK the OSGi manifests are required for the Glassfish integration. But I'm not familiar with the details.

I think we should keep the OSGi manifest. It doesn't do any harm and OSGi is still quite popular. Maybe bnd even supports Java 9 today? Perhaps fixing this would simply be a matter of updating the `maven-bundle-plugin`?

**Comment by spericas** [comment] 2018-05-16 15:00
@mkarg Must have been OSGi. I don't have a problem fixing it to jar.

**Closed** 2018-06-15 21:47 UTC
Labels: enhancement, project

**Comment by kwhat** [comment] 2018-09-26 03:38
So, when is 2.2 being released so I can stop dealing with this problem.

**Comment by mkarg** [comment] 2018-09-26 05:17
I am sorry to say there is no fixed deadline for 2.2, as this depends on ongoing negotiations between Oracle and the Eclipse Foundation.

@spericas @chkal Do you think it would be safe to merge #628 also into `EE4J_8`?

**Comment by spericas** [comment] 2018-09-26 13:56
@mkarg We had to provide a pretty detailed explanation of all the changes that went into EE4J_8 for 2.1.1. I'd rather not check more changes into that branch.

**Comment by mkarg** [comment] 2018-09-26 17:46
@spericas Understood. As I was not involved in that part of the release so dumb question: Did you have to manually write a report or how was this step performed?

**Comment by spericas** [comment] 2018-09-27 15:15
@mkarg It was a manual process. Nothing it could not be done again, of course.

**Comment by mkarg** [comment] 2018-09-27 17:12
@chkal +1
@spericas What do you think?

**Comment by mkarg** [comment] 2018-10-08 05:30
@kwhat I think you can be happy: I just published JAX-RS 2.1.2 on [Maven Central](https://search.maven.org/artifact/jakarta.ws.rs/jakarta.ws.rs-api/2.1.2/bundle) **including** the fix you requested. :-)

**Comment by spericas** [comment] 2018-10-08 13:33
@mkarg Great!
